version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: repsy-postgres
    restart: always
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: repsy-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: