version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: repsy-postgres
    restart: always
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: repsy-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  repository-service:
    image: umutcancerlet/repository-service:latest
    container_name: repsy-repo-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsydb
      SPRING_DATASOURCE_USERNAME: repsyuser
      SPRING_DATASOURCE_PASSWORD: 123456789
      repsy.storage.type: ${STORAGE_TYPE} # environment değişkeninde okunan değere göre depolama yöntemi çekiliyor
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data: