spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/repsydb
    username: repsyuser
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: repository-service

repsy:
  storage:
    type: ${STORAGE_TYPE:filesystem} # ortam değişkeniyle override edilebilir hale getirildi.